services:
  moodle:
    image: bitnami/moodle:latest
    container_name: moodle
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=adminpassword
      - MOODLE_EMAIL=admin@example.com
      - MOODLE_SITE_NAME="My Moodle Site"
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_PASSWORD=moodlepassword
      - MOODLE_DATABASE_NAME=moodle
    volumes:
      - moodle_data:/bitnami/moodle

  mariadb:
    image: mariadb:10.11
    container_name: moodle_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=moodlepassword
    ports:
      - "3306:3306"  
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  moodle_data:
  mariadb_data:
